import { Platform, StyleSheet, ViewStyle } from "react-native";
import { colors } from "./colors";

/**
 * Rewards V2 visual language — faithful to mockups M1–M4
 * (cream/peach child chrome, yellow +N pills, purple history solde).
 */
export const rewardsUi = {
  /** M3 header / soft peach band */
  peach: "#FFD6B6",
  peachSoft: "#FFF1E5",
  /** M3/M4 screen cream */
  cream: "#FFF9F1",
  creamDeep: "#FFF3E6",
  navy: "#1A2B48",
  navyMuted: "#5A6B85",
  /** M3 solde card */
  soldeBlue: "#E8F3FD",
  soldeBlueBorder: "#C5DCF5",
  soldeValue: "#0B72EB",
  /** Uniform yellow/orange +N pills (M2/M3) */
  pillYellow: "#FFE082",
  pillYellowBorder: "#FFB74D",
  pillYellowText: "#E65100",
  /** M2 orange filter / accents */
  filterOrange: "#FF7A3D",
  filterOrangeSoft: "#FFE8DC",
  selectedCream: "#FFEFD9",
  /** M4 purple solde */
  purple: "#6B5CE7",
  purpleSoft: "#F0E8FF",
  purpleDeep: "#5B4BC9",
  purpleCircle: "#7C6CF0",
  /** M4 timeline */
  mint: "#E4F6EC",
  mintBorder: "#B7E4C7",
  greyRow: "#F0F1F3",
  avatarBg: "#F0F3FA",
  navCream: "#FFF6EC",
  navActive: "#FF7A3D",
  cardRadius: 18,
  rowRadius: 14,
  pillRadius: 999,
  shadow: Platform.select({
    ios: {
      shadowColor: "#1C1F2A",
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
    },
    android: { elevation: 2 },
    default: {
      shadowColor: "#1C1F2A",
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
    },
  }) as ViewStyle,
};

export const rewardsStyles = StyleSheet.create({
  screenParent: {
    padding: 14,
    paddingBottom: 24,
    backgroundColor: colors.bg,
  },
  screenKid: {
    padding: 0,
    paddingBottom: 0,
    backgroundColor: rewardsUi.cream,
  },
  screenHistory: {
    padding: 16,
    paddingBottom: 40,
    backgroundColor: rewardsUi.cream,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: rewardsUi.cardRadius,
    padding: 12,
    borderWidth: 0,
    ...rewardsUi.shadow,
  },
  stickyBar: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: Platform.OS === "ios" ? 20 : 12,
    backgroundColor: colors.bg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  infoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 8,
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: "#C9D4FF",
  },
  infoBannerIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  infoBannerIconText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 12,
  },
  infoBannerText: {
    flex: 1,
    color: colors.primary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  avatarCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: rewardsUi.avatarBg,
  },
  avatarEmoji: { fontSize: 26 },
  /** Large yellow +N ⭐ pill — used on M2/M3 task rows */
  pointsPill: {
    backgroundColor: rewardsUi.pillYellow,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1.5,
    borderColor: rewardsUi.pillYellowBorder,
    minHeight: 36,
    minWidth: 64,
    alignItems: "center",
    justifyContent: "center",
  },
  pointsPillText: {
    fontWeight: "900",
    color: rewardsUi.pillYellowText,
    fontSize: 15,
    letterSpacing: 0.2,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: rewardsUi.pillRadius,
    backgroundColor: colors.card,
    borderWidth: 1.5,
    borderColor: colors.border,
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipActiveOrange: {
    backgroundColor: rewardsUi.filterOrange,
    borderColor: rewardsUi.filterOrange,
  },
  filterChipText: { fontWeight: "700", color: colors.text },
  filterChipTextActive: { color: "#fff" },
  unitSeg: {
    flexDirection: "row",
    alignSelf: "flex-start",
    backgroundColor: colors.bg,
    borderRadius: rewardsUi.pillRadius,
    padding: 3,
    borderWidth: 1,
    borderColor: colors.border,
  },
  unitSegItem: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: rewardsUi.pillRadius,
  },
  unitSegItemActive: {
    backgroundColor: colors.primary,
  },
  unitSegText: { fontWeight: "700", color: colors.textMuted, fontSize: 13 },
  unitSegTextActive: { color: "#fff" },
  /** M3 pale-blue solde card */
  soldeCard: {
    backgroundColor: rewardsUi.soldeBlue,
    borderRadius: rewardsUi.cardRadius,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: rewardsUi.soldeBlueBorder,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    ...rewardsUi.shadow,
  },
  soldeStarCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFF8E7",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#FFE0A3",
  },
  soldeStar: { fontSize: 28 },
  soldeLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: rewardsUi.navy,
  },
  soldeValue: {
    fontSize: 28,
    fontWeight: "800",
    color: rewardsUi.soldeValue,
    marginTop: 2,
  },
  /** M4 lavender solde panel */
  soldePurpleCard: {
    backgroundColor: rewardsUi.purpleSoft,
    borderRadius: rewardsUi.cardRadius,
    padding: 16,
    borderWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    ...rewardsUi.shadow,
  },
  soldePurpleStarCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: rewardsUi.purpleCircle,
    alignItems: "center",
    justifyContent: "center",
  },
  soldePurpleValue: {
    fontSize: 28,
    fontWeight: "800",
    color: rewardsUi.purpleDeep,
    marginTop: 2,
  },
  historyCta: {
    marginTop: 8,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: rewardsUi.pillRadius,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: "#fff",
  },
  historyCtaText: {
    fontWeight: "800",
    color: colors.primary,
    fontSize: 14,
  },
  earnRow: {
    backgroundColor: rewardsUi.mint,
    borderColor: rewardsUi.mintBorder,
  },
  resetRow: {
    backgroundColor: rewardsUi.greyRow,
    borderColor: colors.border,
  },
  timelineDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineDotEarn: { backgroundColor: colors.success },
  timelineDotReset: { backgroundColor: colors.textMuted },
  timelineDotText: { color: "#fff", fontSize: 12, fontWeight: "800" },
  /** Decorative cream bottom nav (web look parity) */
  fakeNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    flexShrink: 0,
    paddingTop: 10,
    paddingBottom: Platform.OS === "ios" ? 22 : 12,
    backgroundColor: rewardsUi.navCream,
    borderTopWidth: 1,
    borderTopColor: "#F0E0D0",
    // Keep bar on-screen even if ScrollView content is tall (RN Web).
    zIndex: 30,
  },
  fakeNavItem: { alignItems: "center", gap: 2, minWidth: 72 },
  fakeNavIcon: { fontSize: 20 },
  fakeNavLabel: { fontSize: 11, fontWeight: "700", color: rewardsUi.navyMuted },
  fakeNavLabelActive: { color: rewardsUi.navActive },
});
