import { Platform, StyleSheet, ViewStyle } from "react-native";
import { colors } from "./colors";

/** Shared Rewards V2 visual language (mockups M1–M4). */
export const rewardsUi = {
  peach: "#FFF1E5",
  purple: "#6B5CE7",
  purpleSoft: "#EFEAFE",
  purpleDeep: "#5B4BC9",
  mint: "#E6F7EF",
  greyRow: "#F3F4F6",
  avatarBg: "#F0F3FA",
  cardRadius: 16,
  pillRadius: 999,
  shadow: Platform.select({
    ios: {
      shadowColor: "#1C1F2A",
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
    },
    android: { elevation: 2 },
    default: {
      // web
      shadowColor: "#1C1F2A",
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
    },
  }) as ViewStyle,
};

export const rewardsStyles = StyleSheet.create({
  screenParent: {
    padding: 16,
    paddingBottom: 48,
    backgroundColor: colors.bg,
  },
  screenKid: {
    padding: 16,
    paddingBottom: 48,
    backgroundColor: colors.bg,
  },
  screenHistory: {
    padding: 16,
    paddingBottom: 48,
    backgroundColor: colors.bg,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: rewardsUi.cardRadius,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    ...rewardsUi.shadow,
  },
  infoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginVertical: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: "#C9D4FF",
  },
  infoBannerIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  infoBannerIconText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 12,
  },
  infoBannerText: {
    flex: 1,
    color: colors.primary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  avatarCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: rewardsUi.avatarBg,
  },
  avatarEmoji: { fontSize: 26 },
  pointsPill: {
    backgroundColor: colors.primarySoft,
    borderRadius: rewardsUi.pillRadius,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 0,
  },
  pointsPillText: {
    fontWeight: "800",
    color: colors.primary,
    fontSize: 12,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: rewardsUi.pillRadius,
    backgroundColor: colors.card,
    borderWidth: 1.5,
    borderColor: colors.border,
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipText: { fontWeight: "700", color: colors.text },
  filterChipTextActive: { color: "#fff" },
  unitSeg: {
    flexDirection: "row",
    alignSelf: "flex-start",
    backgroundColor: colors.bg,
    borderRadius: rewardsUi.pillRadius,
    padding: 3,
    borderWidth: 1,
    borderColor: colors.border,
  },
  unitSegItem: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: rewardsUi.pillRadius,
  },
  unitSegItemActive: {
    backgroundColor: colors.primary,
  },
  unitSegText: { fontWeight: "700", color: colors.textMuted, fontSize: 13 },
  unitSegTextActive: { color: "#fff" },
  soldeCard: {
    backgroundColor: colors.card,
    borderRadius: rewardsUi.cardRadius,
    padding: 16,
    borderWidth: 1.5,
    borderColor: "#D6E0FF",
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    ...rewardsUi.shadow,
  },
  soldeStarCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  soldeStar: { fontSize: 28 },
  soldeLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textMuted,
  },
  soldeValue: {
    fontSize: 28,
    fontWeight: "800",
    color: colors.primary,
    marginTop: 2,
  },
  soldePurpleCard: {
    backgroundColor: rewardsUi.purpleSoft,
    borderRadius: rewardsUi.cardRadius,
    padding: 16,
    borderWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    ...rewardsUi.shadow,
  },
  soldePurpleStarCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: rewardsUi.purple,
    alignItems: "center",
    justifyContent: "center",
  },
  soldePurpleValue: {
    fontSize: 28,
    fontWeight: "800",
    color: rewardsUi.purpleDeep,
    marginTop: 2,
  },
  historyCta: {
    marginTop: 10,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: rewardsUi.pillRadius,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: "#fff",
  },
  historyCtaText: {
    fontWeight: "800",
    color: colors.primary,
    fontSize: 14,
  },
  earnRow: {
    backgroundColor: rewardsUi.mint,
    borderColor: "#B7E4C7",
  },
  resetRow: {
    backgroundColor: rewardsUi.greyRow,
    borderColor: colors.border,
  },
  timelineDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineDotEarn: { backgroundColor: colors.success },
  timelineDotReset: { backgroundColor: colors.textMuted },
  timelineDotText: { color: "#fff", fontSize: 11, fontWeight: "800" },
});
